import Head from 'next/head'
import Header from '../components/Header'
import Table from '../components/Table'

export default function Home({data}) {
    data[3].sad = 'S'
    console.log(data[3])
    return (
    <div >
      <Head>
        <title>ONACE - โอแน๊นซ์</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <Table data={data} />
      
    </div>
  )
}

export const getStaticProps = async () =>{
    const url = 'https://rest.coinapi.io/v1/assets/icons/50'
    const config1 = {
        method: 'GET',
        headers: {
            'X-CoinAPI-Key': 'B79CA3D1-F8E4-4F72-93C0-23F003043731' 
        }
    }
    const response = await fetch(url,config1)
    const data = await response.json()
    


    return {
        props: {
            data
        },
    }
}
